### ISSUE TITLE
[Question] Cross referencing CL source code.

### ISSUE THREAD

**Issue by FiV0** [robert-strandh/Concrete-Syntax-Tree#14]
This is a question, so feel free to close is it if goes a bit too much off topic/open ended or you don't have time.

I would like to solve the following problem: Given some CL program, let's say for example:
```
(defparameter str "(defun id (x) x)") ;; line 1                                       
(with-input-from-string (is str) ;; line 2                
    (eclector.concrete-syntax-tree:cst-read is)) ;; line 3
```
I would like to know that `str` on line 2 is referring to `str` on line 1 and `is` on line 3 is referring to `is` on line 2 , `is` on line 2 is essentially a new binding. And as final goal essentially cross referencing a whole project. The whole macro business is making thinks NOT easier. 
The path I wanted to take is something along the lines of 
construct ast with file-location annotation -> macroexpand -> figure out what is bound and what is free.
So I was wondering if this currently possible with this library (or at least parts of it)?
I am also wondering if it is always possible to determine these cross references. 
Feel free to also suggest a completely different approach.

**Comment by scymtym** [comment]
The CST library does very little of what you want. To achieve what you want, you need:
* A parser for Common Lisp's character-based syntax
  * With source tracking ([eclector](https://github.com/robert-strandh/eclector) can do that)
  * Depending on how you want this to work, interning symbols, read-time evaluation, etc may not be desirable (eclector can be customized in this regard, but it is not an out-of-the-box functionality)
* Parse Common Lisp's s-expression syntax, maybe producing an AST, preserving source locations
* Expand macros, preserving source locations (Concrete-Syntax-Tree can help re-attaching source locations to the result of macro-expansion)
* Interpret special forms and potentially standard macros

At the moment, no readily available library or combination of libraries (that I am aware of) does all that.

**Comment by FiV0** [comment]
Ok. Thank you anyway. 
I guess I will use Eclector's `cst-read` with some specialization on the source tracking and see where I'll go from there.
