### ISSUE TITLE
Probable type declarations are silently ignored

### ISSUE THREAD

**Issue by Bike** [robert-strandh/Concrete-Syntax-Tree#19]
`canonicalize-declaration-specifier` ignores declarations it doesn't specifically handle. At the moment this seems to include all declarations other than the standard ones. This includes types, like the `(declare (cons x))` synonym for `(declare (type cons x))`. The overall consequence is that this sort of declaration is silently ignored by Cleavir, which is bad.

This behavior is caused by the default method here: https://github.com/robert-strandh/Concrete-Syntax-Tree/blob/master/declarations.lisp#L18-L20

Brief review of the declaration semantics: `(typespec var*) is an abbreviation for (type typespec var*).` according to the Notes on the page for the `type` declaration. I don't see this specified anywhere else, so I suppose technically this isn't part of the standard (because Notes sections aren't), but given how universal the syntax is I think supporting it is basically required.

Now `typespec` there is a type specifier, but there's no good way to tell what is and isn't a valid type specifier really, or at least certainly not one that won't involve interrogating the environment, and interrogating the environment is outside the scope of CST.

An additional wrinkle is the `declaration` proclamation (i.e. not valid in local `declare`), which can be used by a programmer to indicate that a declaration identifier is valid but should be ignored. I've never seen this in code younger than I am but it's part of the standard.

It would be possible to move this functionality out of CST to somewhere that can deal with environments, but I don't think that's necessary. An easier solution would be to treat any unrecognized declaration identifier, at least if it's a symbol or cons, as a type declaration. This is simple and I believe almost entirely correct in reference to real code. If this isn't the case it's likely whatever's using CST (e.g. Cleavir) would check the validity of type specifiers while processing canonicalized `type` declarations anyway.

To support `declaration`, an additional parameter of proclaimed declaration identifiers could be added. Then the canonicalizer could simply ignore any identifier in this list, and treat the rest as type specifiers.

**Comment by robert-strandh** [comment]
The standard requires (typespec var*) to be an abbreviation for
(type typespec var*) as the syntax for the TYPE declaration shows.

**Comment by robert-strandh** [comment]
I agree with your analysis and your suggested solutions.  A simple, but not quite
correct solution would be to treat any unrecognized declaration identifier as a 
type specifier.  The only correct solution that I see would be to add a parameter
with proclaimed declaration identifiers.  I considered the possibility of canonicalizing
all the unknown ones as just bundling together all the similar ones, but that
would be incorrect in the presence of proclaimed declaration identifiers that
(like type and ftype) take an additional parameter.

**Comment by Bike** [comment]
Fixed by #20
